version: '3'

services:
  app:
    build: .
    depends_on:
      - mariadb
    networks:
      - tweet-elite
    volumes:
      - ./:/app

  mariadb:
    image: mariadb:latest
    ports:
      - '3310:3306'
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - tweet-elite
    volumes:
      - mariadb_tweet_elite:/var/lib/mysql

networks:
  tweet-elite:
    driver: bridge

volumes:
  mariadb_tweet_elite:
