version: '3'

services:
  app:
    container_name: teb-be
    build: .
    entrypoint: >
      sh -c "cd /app && npm run migrate:up && node index.js"
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
    networks:
      - tweet-elite
    volumes:
      - ./:/app
      - /app/node_modules

  mariadb:
    container_name: teb-mariadb
    image: mariadb:latest
    ports:
      - '3310:3306'
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - tweet-elite
    volumes:
      - mariadb_tweet_elite:/var/lib/mysql

  phpmyadmin:
    container_name: teb-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '81:80'
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - tweet-elite

networks:
  tweet-elite:
    driver: bridge

volumes:
  mariadb_tweet_elite:
