@api = http://localhost:3000

POST {{api}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123"
}

###

GET {{api}}/users/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZF9hZG1pbiI6NCwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHZKUU9aRVNoc3ZjTFJsQy9wV0gudHVJbTlVZENmUERDeFFjTUsvLnVMem5vcjh5UU13cVJDIn0sImlhdCI6MTY5NDkzNTY4MSwiZXhwIjoxNjk1MDIyMDgxfQ.rUsnKfiRCgDu1k0h409UDD5pJkNDTbjcmLQz_xcqsl8

###